module.exports = {
  drivingOffencesQuestions: '.driving-offences-question',
  drivingOffenceType: '#drivingOffenceTypeQuestion',
  drivingOffenceTypeCodeOther: 'input[name=drivingOffenceCodeOtherField]',
  drivingOffenceCode: '#drivingOffenceCodeQuestion',
  drivingOffenceCodeOther: 'input[name=drivingOffenceTypeOtherField]',
  drivingOffenceAlcoholReading: '#drivingOffenceAlcoholReading',
  drivingOffenceDate: '#drivingOffenceDateQuestion',
  drivingOffenceDateDay: 'input[name=drivingOffenceDate-DD]',
  drivingOffenceDateMonth: 'input[name=drivingOffenceDate-MM]',
  drivingOffenceDateYear: 'input[name=drivingOffenceDate-YYYY]',
  drivingOffencePenaltyPoints: '#drivingOffencePenaltyPointsQuestion',
  drivingOffencePointsOther: 'select[name=drivingOffencePointsOther]',
  drivingOffencePaidFine: '#drivingOffencePaidFineQuestion',
  drivingOffenceFineAmount: '#drivingOffenceFineAmount',
  drivingOffenceBanned: '#drivingOffenceBannedQuestion',
  drivingOffenceMonthsBanned: '#drivingOffenceMonthsBanned',
  saveDrivingOffence: '.driving-offences-question .btn--subprimary',
  addAnotherDrivingOffence: '.driving-offences-question .btn--subprimary',
  removeDrivingOffences: '#drivingOffencesPreviewQuestion',
  drivingOffencesRemoval: '#drivingOffencesRemovalQuestion',
  drivingOffencesRemovalConfirm: '#drivingOffencesRemovalQuestion .btn--subprimary',
  drivingOffencesRemovalCancel: '#drivingOffencesRemovalQuestion .btn--link'
};